name: Test Hola Mundo + Notificación

on:
  push:
    branches:
      - main

jobs:
  test-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Ejecutar test hola.js
        id: test_hola
        run: |
          OUTPUT=$(node holala.js)
          echo "Salida del programa: $OUTPUT"

          if [ "$OUTPUT" != "hola mundo" ]; then
            echo "❌ Test falló"
            exit 1
          fi

          echo "✅ Test pasó correctamente"

      - name: Enviar notificación a ntfy
        if: success()
        run: |
          curl -d "✅ Test exitoso" https://ntfy.sh/devops-itla

