name: Alerta Push a Main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificaciÃ³n a ntfy
        run: |
          curl -X POST https://ntfy.sh/devops-itla \
            -H "Title: ðŸš€ Se ha hecho push a main.. att elvyscruz" \
            -H "Tags: github,deploy,main" \
            -H "Priority: 4" \
            -d "Repositorio: ${{ github.repository }}
